version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  node-express:
    image: node:14
    container_name: node-express
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://localhost:27017
        labels:
      - traefik.enable=true
      - traefik.http.routers.mushroompy.entryPoints=websecure 
      - traefik.http.routers.mushroompy.rule=Host(`mushroompy.jrcandev.netlib.re`)
      - traefik.http.routers.mushroompy.tls=true  
      - traefik.http.routers.mushroompy.tls.certresolver=myresolver
volumes:
  mongodb_data:

networks:
  web:
    external: true
  lan:
    external: false
    name: lan_mushroompy
