version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  nodejs-express-app:
    image: node:latest
    container_name: nodejs-express-app
    working_dir: /app
    volumes:
      - ./path/to/your/nodejs/app:/app  
    ports:
      - "3200:3200"  
    depends_on:
      - mongodb

volumes:
  mongodb_data:
