version: '3.8'

services:
  backend:
    image: node:18
    container_name: backend-container
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb-container:27017/Mush
    command: bash -c "npm install && npm start"
    depends_on:
      - mongodb
    networks:
      - my-network

  mongodb:
    image: mongo:4.4
    container_name: mongodb-container
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
    networks:
      - my-network

  frontend:
    image: node:14
    container_name: frontend-container
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "80:8080"
    command: bash -c "npm install axios && npm install && npm run serve"
    networks:
      - my-network

networks:
  my-network:
    driver: bridge
