version: '3'

services:
  # Service Node.js avec Express pour le backend
  backend:
    image: node:14
    container_name: backend-container
    working_dir: /app/backend
    volumes:
      - ./backend:/app/backend
    ports:
      - "3000:3000"
    environment:
      MONGO_URI: mongodb://mongodb:27017/Mush
    command: bash -c "npm install && npm start"
    networks:
      - web
      - lan

  # Service MongoDB
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    ports:
      - "27017:27017"
    networks:
      - web
      - lan

  # Service Node.js avec Express pour le frontend (facultatif)
  frontend:
    image: node:14
    container_name: frontend-container
    working_dir: /app/frontend
    volumes:
      - ./frontend:/app/frontend
    command: bash -c "npm install && npm run serve"
    labels:
      - traefik.enable=true
      - traefik.http.routers.mushroompy.entryPoints=websecure
      - traefik.http.routers.mushroompy.rule=Host(`mushroompy.jrcandev.netlib.re`)
      - traefik.http.routers.mushroompy.tls=true
      - traefik.http.routers.mushroompy.tls.certresolver=myresolver
      - traefik.http.services.mushroompy.loadbalancer.server.port=8080
    networks:
      - web
      - lan

networks:
  web:
    external: true
  lan:
    external: false
    name: lan_mushroompy
