name: Python Application Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # or any other version of Python you're using

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt6 requests  # Add any other dependencies you need

    - name: Run test
      run: |
        python Appli_Python/test_downloadThread.py
